### PR TITLE
validation in BagMoveJob

### PR DESCRIPTION
**Pull request by aelkiss**
- validates bags
- runs external validation command

N.B. I haven't run an integration test (i.e. running it through the CLI to see if it works), just the specs in `bag_move_job_spec.rb` with mocked `ChipmunkBag` & `Open3`.

### CODE REVIEW

**Comment by aelkiss** [comment]
I ran an end-to-end test with the uploader that triggered an external validation command that just looked to see if the bag contained `data/samplefile`. I needed to actually add the uploaded bag path to the validation cmd that gets run (5328e17) but other than that looks fine

**Comment by malakai97** [comment]
bag_move_job.rb

I'm concerned that `bag_is_valid?` and `externally_validates?` both modify and save the record. Essentially, their internal `else` clauses make up the `else` clause of the if-statement they're invoked by.   This goes beyond the common errors-hash population that methods like `valid?` perform. 

I'm okay with still merging this now and just rolling forward an issue to refactor this bit.

**Comment by aelkiss** [comment]
Something to add to PFDR-63, for sure. Keeping track of the errors is the part that requires a little bit of thought; I guess we could just record them in an `@errors` instance variable and then do something like

```ruby
if bag_is_valid? and externally_validates?
        File.rename(src_path,dest_path)
        record_success
else
        record_failure
end

def record_failure
    queue_item.transaction do
      queue_item.error = @error.to_s
      queue_item.status = :failed
      queue_item.save!
    end
  end
end
```

That seems simple enough it might be worth adding on to this PR, thoughts?

**Comment by malakai97** [comment]
That looks much better.  Populating an `@errors` member is a pretty common side effect for those sorts of validations.

**Pull request merged**
