### PR TITLE
PFDR-121 - Modernize documentation 

### PR DESCRIPTION
**Pull request by malakai97**
_(This post updated 2019-04-03)_

## Update documentation strategy and content

Resolves PFDR-121

* Add YARD / rubydoc.info
* Add sphinx / ReadTheDocs
* Add coveralls
* Add badges
* Moved the readme's contents to the new contributing page
* Removed copy of preservation principles doc (PRINCIPLES.md), and just
  link to the primary source in confluence.
* Document endpoints
* Document workflows with plantuml
* Migrate most documentation to sphinx away from the wiki, readme
* Include instructions for building documentation

Please take a look at index.rst, as I tried to fill that out with information from the digital preservations principles doc.

### CODE REVIEW

**Comment by aelkiss** [comment]
The current routes are:

```
aelkiss@qoo:~/Repositories/chipmunk$ be rake routes
        Prefix Verb URI Pattern                             Controller#Action
   v1_requests GET  /v1/requests(.:format)                  v1/packages#index
               POST /v1/requests(.:format)                  v1/packages#create
    v1_request GET  /v1/requests/:bag_id(.:format)          v1/packages#show
            v1 POST /v1/requests/:bag_id/complete(.:format) v1/queue_items#create
   v1_packages GET  /v1/packages(.:format)                  v1/packages#index
    v1_package GET  /v1/packages/:bag_id(.:format)          v1/packages#show
               GET  /v1/packages/:bag_id/events(.:format)   v1/events#index
               GET  /v1/packages/:bag_id/:file(.:format)    v1/packages#sendfile {:file=>/.*/}
     v1_events GET  /v1/events(.:format)                    v1/events#index
       v1_bags GET  /v1/bags(.:format)                      v1/packages#index
        v1_bag GET  /v1/bags/:bag_id(.:format)              v1/packages#show
               GET  /v1/bags/:bag_id/events(.:format)       v1/events#index
v1_queue_items GET  /v1/queue(.:format)                     v1/queue_items#index
 v1_queue_item GET  /v1/queue/:id(.:format)                 v1/queue_items#show
     v1_audits GET  /v1/audits(.:format)                    v1/audits#index
               POST /v1/audits(.:format)                    v1/audits#create
      v1_audit GET  /v1/audits/:id(.:format)                v1/audits#show
         login GET  /login(.:format)                        users#login
```

Of these, the following should be marked as deprecated in favor of packages in the docs:

```
       v1_bags GET  /v1/bags(.:format)                      v1/packages#index
        v1_bag GET  /v1/bags/:bag_id(.:format)              v1/packages#show
               GET  /v1/bags/:bag_id/events(.:format)       v1/events#index
```

The following new routes should be documented:

```
   v1_packages GET  /v1/packages(.:format)                  v1/packages#index
    v1_package GET  /v1/packages/:bag_id(.:format)          v1/packages#show
               GET  /v1/packages/:bag_id/events(.:format)   v1/events#index
               GET  /v1/packages/:bag_id/:file(.:format)    v1/packages#sendfile {:file=>/.*/}
     v1_audits GET  /v1/audits(.:format)                    v1/audits#index
               POST /v1/audits(.:format)                    v1/audits#create
      v1_audit GET  /v1/audits/:id(.:format)                v1/audits#show
     v1_events GET  /v1/events(.:format)                    v1/events#index
```

We still have some cleanup to do around request. We might want to just create a v2 of the API that collapses everything into package and removes the bag & request routes entirely. I think that could all be done just at the route level.

**Comment by malakai97** [comment]
Pay close attention to the audits and events because it wasn't totally clear what these were. The docs should definitely describe that information, either in the API or elsewhere.

**Comment by malakai97** [comment]
This is now ready. Please take a look at `index.rst`, as I tried to fill that out with information from the digital preservations principles doc.

**Comment by malakai97** [comment]
Top post updated.

**Comment by malakai97** [comment]
Per the channel, I've added the preservation principles back, as `docs/principles.rst`. It should render identically to before.

**Pull request merged**
